export const menu = [
  {
    text: "CAMPANHA",
    href: "",
    icon: "fa fa-umbrella",
    target: "_self",
    title: "",
    site_menu_type: "menu",
    site_href: "",
    parameters: "",
    internal: "/campanhas",
    site_visible: "1",
    app_menu_type: "menu",
    app_href: "",
    app_screen: "",
    mobile_view: "",
    app_visible: "1",
    access_groups: ["1"],
    children: [
      {
        text: "CAMPANHAS",
        href: "",
        icon: "fa fa-bullhorn",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/campanhas",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/campanhas&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
      {
        text: "REGULAMENTO",
        href: "",
        icon: "fa fa-book",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/regulamento",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/regulamento&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
      {
        text: "COMO PARTICIPAR",
        href: "",
        icon: "fa fa-gears",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/como-participar",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/como-participar&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
      {
        text: "FOTOS",
        href: "",
        icon: "fa fa-camera",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/fotos",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/fotos&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
    ],
  },
  {
    text: "EXTRATO",
    href: "",
    icon: "fa fa-money",
    target: "_self",
    title: "",
    site_menu_type: "internal",
    site_href: "",
    parameters: "",
    internal: "/metas-e-apuracoes",
    site_visible: "1",
    app_menu_type: "mobile_view",
    app_href: "",
    app_screen: "",
    mobile_view: "/metas-e-apuracoes&mobile_popup=true",
    app_visible: "1",
    access_groups: ["1"],
  },
  {
    text: "TREINAMENTOS",
    href: "",
    icon: "fa fa-caret-square-o-right",
    target: "_self",
    title: "",
    site_menu_type: "internal",
    site_href: "",
    parameters: "",
    internal: "/treinamentos",
    site_visible: "1",
    app_menu_type: "mobile_view",
    app_href: "",
    app_screen: "",
    mobile_view: "/treinamentos&mobile_popup=true",
    app_visible: "1",
    access_groups: ["1"],
  },
  {
    text: "NOTICIAS",
    href: "",
    icon: "fa fa-newspaper-o",
    target: "_self",
    title: "",
    site_menu_type: "internal",
    site_href: "",
    parameters: "",
    internal: "/noticias",
    site_visible: "1",
    app_menu_type: "mobile_view",
    app_href: "",
    app_screen: "",
    mobile_view: "/noticias&mobile_popup=true",
    app_visible: "1",
    access_groups: ["1"],
  },
  {
    text: "CONTATO",
    href: "",
    icon: "fa fa-at",
    target: "_self",
    title: "",
    site_menu_type: "menu",
    site_href: "",
    parameters: "",
    internal: "/campanhas",
    site_visible: "1",
    app_menu_type: "menu",
    app_href: "",
    app_screen: "",
    mobile_view: "",
    app_visible: "1",
    access_groups: ["1"],
    children: [
      {
        text: "FALE CONOSCO",
        href: "",
        icon: "fa fa-comment-o",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/fale-conosco",
        site_visible: "1",
        app_menu_type: "app_screen",
        app_href: "",
        app_screen: "ContactUs",
        mobile_view: "/fale-conosco&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
      {
        text: "FAQ",
        href: "",
        icon: "fa fa-anchor",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/faq",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/faq&mobile_popup=true",
        app_visible: "1",
        access_groups: ["1"],
      },
    ],
  },
  {
    text: "CATÁLOGO DE PRÊMIOS",
    href: "",
    icon: "fa fa-gift",
    target: "_blank",
    title: "",
    site_menu_type: "internal",
    site_href: "",
    parameters: "",
    internal: "/catalogo",
    site_visible: "1",
    app_menu_type: "external_link",
    app_href:
      "https://hlg.markup.com.br/premioideall/LoginIntegracao.aspx?CPF={{cpf_base64}}&campanha=MTQ=",
    app_screen: "",
    mobile_view: "/catalogo",
    app_visible: "1",
    access_groups: ["1"],
  },
  {
    text: "RELATÓRIOS",
    href: "",
    icon: "fa fa-bars",
    target: "_self",
    title: "",
    site_menu_type: "menu",
    site_href: "",
    parameters: "",
    internal: "/aprovacao-de-cadastros",
    site_visible: "1",
    app_menu_type: "menu",
    app_href: "",
    app_screen: "",
    mobile_view: "",
    app_visible: "0",
    access_groups: [],
    children: [
      {
        text: "CADASTRO",
        href: "",
        icon: "",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/relatorio/relatorio-participantes",
        site_visible: "1",
        app_menu_type: "",
        app_href: "",
        app_screen: "",
        mobile_view: "",
        app_visible: "0",
        access_groups: ["5"],
      },
    ],
  },
  {
    text: "ADMIN",
    href: "",
    icon: "fa fa-gears",
    target: "_self",
    title: "",
    site_menu_type: "menu",
    site_href: "",
    parameters: "",
    internal: "/aprovacao-de-cadastros",
    site_visible: "1",
    app_menu_type: "menu",
    app_href: "",
    app_screen: "",
    mobile_view: "",
    app_visible: "0",
    access_groups: [],
    children: {
      "2": {
        text: "DASH CADASTRO",
        href: "",
        icon: "fa fa-bar-chart-o",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/dashboards/registers-participants",
        site_visible: "1",
        app_menu_type: "",
        app_href: "",
        app_screen: "",
        mobile_view: "/dashboards/registers&mobile_popup=true",
        app_visible: "0",
        access_groups: ["5"],
      },
      "3": {
        text: "DASH ACESSO",
        href: "",
        icon: "fa fa-bar-chart-o",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/dashboards/access",
        site_visible: "1",
        app_menu_type: "",
        app_href: "",
        app_screen: "",
        mobile_view: "/dashboards/access&mobile_popup=true",
        app_visible: "0",
        access_groups: ["5"],
      },
      "4": {
        text: "DASH COMUNICAÇÃO",
        href: "",
        icon: "fa fa-bar-chart-o",
        target: "_self",
        title: "",
        site_menu_type: "internal",
        site_href: "",
        parameters: "",
        internal: "/dashboards/communications",
        site_visible: "1",
        app_menu_type: "mobile_view",
        app_href: "",
        app_screen: "",
        mobile_view: "/dashboards/communications&mobile_popup=true",
        app_visible: "1",
        access_groups: ["5"],
      },
    },
  },
];
